name = "med-appointment"
main = "src/worker.ts"
compatibility_date = "2026-04-24"

[[d1_databases]]
binding = "DB"
database_name = "med_appointment_db"
database_id = "479dea3e-3075-49db-a0c1-22d7781e05a4"

[assets]
directory = "./dist"
binding = "ASSETS"
