import type { Appointment } from "../types";

export const createDefaultAppointmentDraft = (): Partial<Appointment> => ({
  status: "Scheduled",
  residentId: "",
  residentMrn: "",
  residentName: "",
  origin: "",
  unit: "",
  roomNumber: "",
  providerName: "",
  location: "",
  contactNumber: "",
  schedulingDate: "",
  referralDate: "",
  date: "",
  time: "",
  pickUpTime: "",
  type: "",
  description: "",
  serviceInHouse: "",
  reasonSendOut: "",
  transportType: "",
  transportCompany: "",
  transportCompanyId: "",
  transportCompanyPhone: "",
  transportCompanyOther: "",
  payerForRide: "",
  roundTrip: "",
  escort: "",
  escortPhone: "",
  notes: "",
  reasonConsultation: "",
  consultReason: "",
});
