export const CONSULT_REASONS_BY_SPECIALTY: Record<string, string[]> = {
  "Dental": [
    "Routine dental checkup and cleaning for preventive oral care.",
    "Evaluation and treatment of tooth pain, gum pain, abscess, or suspected oral infection.",
    "Denture evaluation, adjustment, repair, or replacement.",
    "Evaluation of oral health concerns affecting chewing, nutrition, or overall health.",
    "Evaluation of dry mouth or oral symptoms possibly related to medications.",
    "Dental clearance prior to surgery or medical procedure.",
    "Evaluation for dental extraction, filling, periodontal treatment, or other specialized procedure.",
    "Evaluation of oral cavity, gum lesion, growth, or abnormal finding to rule out malignancy.",
    "Evaluation of dysphagia or chewing difficulty possibly related to dental issues.",
    "Evaluation of broken tooth, loose tooth, or dental trauma."
  ],
  "Cardiology": [
    "Routine cardiac follow-up for chronic heart condition monitoring.",
    "Management of coronary artery disease, heart failure, or other cardiac disease.",
    "Evaluation of arrhythmia, irregular heartbeat, or abnormal heart rhythm.",
    "Cardiac medication review or adjustment.",
    "Evaluation for cardiac diagnostic testing such as EKG, echocardiogram, or stress test.",
    "Cardiac clearance prior to surgery or procedure.",
    "Evaluation of chest pain, shortness of breath, edema, or cardiac-related symptoms.",
    "Pacemaker, AICD, or cardiac device check.",
    "Evaluation of uncontrolled hypertension.",
    "Evaluation of syncope or near-syncope episode."
  ],
  "Optometry": [
    "Routine vision exam.",
    "Evaluation for eyeglass or contact lens prescription update.",
    "Screening or monitoring for glaucoma, cataracts, macular degeneration, or other eye conditions.",
    "Diabetic eye screening or follow-up.",
    "Evaluation of blurred vision, eye strain, headaches, or other vision-related symptoms.",
    "Low vision assessment and support.",
    "Follow-up after eye surgery or procedure.",
    "Specialized vision testing not available in-house.",
    "Evaluation of difficulty reading, watching TV, or completing ADLs due to vision decline."
  ],
  "Ophthalmology": [
    "Comprehensive eye examination for disease detection or management.",
    "Cataract evaluation or post-cataract surgery follow-up.",
    "Glaucoma management and eye pressure monitoring.",
    "Diabetic retinopathy screening or follow-up.",
    "Treatment of eye infection, inflammation, conjunctivitis, or uveitis.",
    "Macular degeneration evaluation or management.",
    "Evaluation of sudden vision loss, acute vision change, or worsening blurred vision.",
    "Specialized testing such as OCT, visual field testing, or eye imaging."
  ],
  "Audiology": [
    "Routine hearing assessment.",
    "Hearing aid evaluation, adjustment, repair, or fitting.",
    "Evaluation and management of hearing loss.",
    "Evaluation of balance or dizziness possibly related to inner ear disorder.",
    "Earwax removal or evaluation of impacted cerumen.",
    "Follow-up after ear infection.",
    "Communication support due to hearing difficulty.",
    "Audiogram or specialized hearing test.",
    "Evaluation of sudden hearing loss."
  ],
  "ENT": [
    "Evaluation of chronic or recurrent ear infections.",
    "Evaluation of hearing issues or ear-related concerns.",
    "Evaluation of dizziness, vertigo, or balance problems.",
    "Evaluation of chronic sinusitis, nasal obstruction, or nasal symptoms.",
    "Evaluation of swallowing difficulty, hoarseness, sore throat, or throat disorder.",
    "Evaluation of sleep apnea or airway-related breathing issue.",
    "Removal or evaluation of impacted cerumen.",
    "Evaluation of ENT growth, mass, polyp, cyst, or tumor.",
    "Evaluation of chronic cough or persistent hoarseness.",
    "Evaluation of swallowing issues suspected to be ENT-related."
  ],
  "Dermatology": [
    "Skin cancer screening or evaluation of suspicious lesion.",
    "Management of chronic skin condition such as eczema, psoriasis, or dermatitis.",
    "Evaluation of wound, ulcer, pressure injury, or non-healing skin lesion.",
    "Evaluation of rash, allergic reaction, or unexplained skin change.",
    "Evaluation and treatment of fungal, bacterial, or viral skin infection.",
    "Evaluation of fragile skin, bruising, dryness, or age-related skin changes.",
    "Removal or treatment of wart, cyst, lipoma, or benign skin growth.",
    "Evaluation of possible medication-related skin reaction.",
    "Evaluation of skin lesion or growth to rule out malignancy.",
    "Skin lesion biopsy.",
    "Skin malignancy management or treatment.",
    "Evaluation of chronic pruritus or itching.",
    "Evaluation of hair or scalp disorder, including alopecia or scalp dermatitis."
  ],
  "Endocrinology": [
    "Diabetes management and blood glucose control review.",
    "Evaluation or management of thyroid disorder.",
    "Evaluation of adrenal, pituitary, or hormonal imbalance.",
    "Osteoporosis evaluation or treatment management.",
    "Endocrine medication review or adjustment.",
    "Screening or prevention of diabetes/endocrine-related complications.",
    "Specialized endocrine lab work or imaging.",
    "Follow-up after endocrine-related hospitalization.",
    "Evaluation of adrenal or pituitary mass.",
    "Evaluation of hypoglycemia episodes."
  ],
  "Gastroenterology / GI": [
    "Management of GERD, IBS, chronic constipation, or chronic digestive disorder.",
    "Evaluation for colonoscopy, endoscopy, or GI disease screening.",
    "Evaluation of abdominal pain or unexplained GI discomfort.",
    "Management of liver, hepatitis, cirrhosis, pancreatic, or related condition.",
    "Evaluation of malabsorption, weight loss, poor intake, or nutritional concern.",
    "Evaluation of GI bleeding, blood in stool, or vomiting blood.",
    "Evaluation of GI symptoms possibly related to medications.",
    "Follow-up after GI-related hospitalization.",
    "PEG site or stoma evaluation, malfunction, or management.",
    "Evaluation of unexplained weight loss.",
    "Evaluation of dysphagia."
  ],
  "Hematology": [
    "Evaluation and management of anemia or low hemoglobin.",
    "Evaluation of bleeding disorder or clotting disorder.",
    "Management of chronic blood disorder such as leukemia, lymphoma, or myeloma.",
    "Evaluation of abnormal CBC, platelet count, or blood count abnormality.",
    "Anticoagulation or hematology-related medication monitoring.",
    "Evaluation of vitamin B12, folate, iron deficiency, or nutritional deficiency.",
    "Follow-up after hematology-related hospitalization.",
    "Bone marrow biopsy or specialized hematology testing.",
    "Chemotherapy-related follow-up or management.",
    "Oncology/hematology management.",
    "Evaluation of unexplained bruising or bleeding."
  ],
  "Oncology": [
    "Cancer diagnosis, staging, or treatment planning.",
    "Chemotherapy or radiation therapy follow-up.",
    "Management of cancer-related symptoms such as pain, fatigue, nausea, or weakness.",
    "Screening or monitoring for cancer recurrence.",
    "Cancer-related medication review or adjustment.",
    "Evaluation of abnormal lab, imaging, or suspicious diagnostic result.",
    "Palliative care planning related to cancer diagnosis.",
    "Post-surgical oncology follow-up.",
    "Evaluation of new mass, lump, or lymphadenopathy."
  ],
  "Infectious Disease": [
    "Management of chronic infection such as hepatitis, HIV, or long-term infection.",
    "Evaluation of recurrent infections, including urinary, respiratory, or skin infections.",
    "Antibiotic stewardship review or long-term antibiotic management.",
    "Evaluation and treatment of multidrug-resistant organism infection.",
    "Follow-up after sepsis or serious infection hospitalization.",
    "Evaluation of fever of unknown origin.",
    "Vaccination guidance for high-risk or immunocompromised resident.",
    "Specialized infectious disease testing or diagnostic review.",
    "Evaluation of chronic wound infection.",
    "Evaluation or management of recurrent C. difficile infection."
  ],
  "Nephrology": [
    "Chronic kidney disease monitoring and management.",
    "Dialysis follow-up and complication management.",
    "Evaluation of electrolyte imbalance such as sodium, potassium, or calcium abnormality.",
    "Kidney-related medication review or dose adjustment.",
    "Evaluation of edema, swelling, or fluid retention.",
    "Management of hypertension related to kidney disease.",
    "Evaluation of abnormal renal labs such as elevated BUN, creatinine, or decreased GFR.",
    "Follow-up after acute kidney injury or renal-related hospitalization.",
    "Pre-dialysis evaluation.",
    "Kidney disease-related diagnostic procedure.",
    "Evaluation of recurrent UTIs with possible renal involvement."
  ],
  "Neurology": [
    "Stroke follow-up and prevention management.",
    "Dementia, Alzheimer’s disease, or cognitive decline evaluation.",
    "Parkinson’s disease management.",
    "Evaluation and management of seizure disorder or new-onset seizure.",
    "Evaluation of neuropathy, nerve pain, tingling, numbness, or weakness.",
    "Evaluation of chronic headache or migraine.",
    "Evaluation of tremor, gait abnormality, movement disorder, or coordination problem.",
    "EEG, EMG, imaging review, or other neurologic diagnostic testing.",
    "Evaluation of recurrent falls suspected to be neurologic in nature.",
    "Tremor evaluation."
  ],
  "Neuropsychology": [
    "Cognitive assessment for memory, attention, reasoning, or problem-solving.",
    "Dementia diagnosis, differentiation, or progression monitoring.",
    "Evaluation of behavioral changes, mood changes, aggression, or personality changes.",
    "Post-stroke cognitive evaluation.",
    "Depression or anxiety screening related to cognitive or functional status.",
    "Evaluation of medication impact on cognition or behavior.",
    "Capacity evaluation for decision-making or care planning.",
    "Rehabilitation planning for cognitive or functional improvement.",
    "Evaluation for guardianship or POA capacity."
  ],
  "Psychology": [
    "Depression evaluation or management.",
    "Anxiety evaluation or management.",
    "Behavioral change evaluation, including agitation, aggression, irritability, or withdrawal.",
    "Adjustment support related to nursing-home placement or change in condition.",
    "Grief counseling.",
    "Coping support for chronic illness or functional decline.",
    "Stress reduction and coping skills therapy.",
    "Cognitive Behavioral Therapy or supportive counseling.",
    "Evaluation of refusal of care possibly related to psychological distress."
  ],
  "OB/GYN": [
    "Routine gynecological exam.",
    "Management of menopausal symptoms.",
    "Evaluation of pelvic pain.",
    "Screening for gynecologic cancer.",
    "Evaluation or treatment of vaginal infection, urinary symptoms, or gynecologic infection.",
    "Hormone therapy monitoring.",
    "Post-surgical gynecologic follow-up.",
    "Evaluation of abnormal vaginal bleeding.",
    "Pelvic organ prolapse evaluation."
  ],
  "Orthopedics": [
    "Fracture follow-up and healing evaluation.",
    "Evaluation of joint pain, arthritis, or degenerative joint disease.",
    "Evaluation of mobility problems, gait difficulty, or difficulty walking.",
    "Post-operative follow-up after hip, knee, spine, or orthopedic surgery.",
    "Osteoporosis-related fracture prevention or bone health management.",
    "Treatment of sprain, strain, dislocation, or musculoskeletal injury.",
    "Prosthetic, brace, splint, or orthopedic device adjustment.",
    "Review of X-ray, MRI, CT scan, or orthopedic imaging.",
    "Surgical site staple or suture removal.",
    "Evaluation of possible surgical site infection.",
    "Update or clarification of weight-bearing status.",
    "Post-surgical drainage device removal.",
    "Contracture management evaluation."
  ],
  "Podiatry": [
    "Routine foot care, nail trimming, callus care, or foot maintenance.",
    "Diabetic foot evaluation or management.",
    "Evaluation of foot pain, bunion, arthritis, or plantar fasciitis.",
    "Evaluation of fungal nails, ingrown toenail, corn, or skin/nail condition.",
    "Evaluation or treatment of foot wound or non-healing ulcer.",
    "Gait evaluation, orthotic recommendation, or supportive footwear assessment.",
    "Evaluation of poor circulation or peripheral vascular disease affecting the feet.",
    "Post-surgical foot or ankle follow-up."
  ],
  "Pulmonology": [
    "COPD, emphysema, chronic bronchitis, or chronic lung disease management.",
    "Asthma monitoring and treatment adjustment.",
    "Evaluation of shortness of breath or worsening respiratory symptoms.",
    "Sleep apnea evaluation or management.",
    "Follow-up after pneumonia.",
    "Oxygen therapy review or adjustment.",
    "Pulmonary function test, chest imaging, bronchoscopy, or specialized testing.",
    "Management of recurrent or severe respiratory infection.",
    "Evaluation of BiPAP/CPAP need, tolerance, or setting adjustment.",
    "Evaluation of chronic cough."
  ],
  "Surgery": [
    "Pre-surgical evaluation or surgical clearance.",
    "Post-surgical follow-up and wound healing assessment.",
    "Surgical wound management or non-healing surgical wound evaluation.",
    "Evaluation of surgical complication such as pain, infection, drainage, or poor healing.",
    "Planning for elective surgical procedure.",
    "Review of imaging, diagnostic test, or lab result related to surgical decision.",
    "Device, implant, drain, or surgical hardware evaluation.",
    "Surgical second opinion.",
    "Drain or tube removal.",
    "Evaluation of surgical hernia."
  ],
  "General Surgery": [
    "Pre-surgical evaluation or surgical clearance.",
    "Post-surgical follow-up and wound healing assessment.",
    "Surgical wound management or non-healing surgical wound evaluation.",
    "Evaluation of surgical complication such as pain, infection, drainage, or poor healing.",
    "Planning for elective surgical procedure.",
    "Review of imaging, diagnostic test, or lab result related to surgical decision.",
    "Device, implant, drain, or surgical hardware evaluation.",
    "Surgical second opinion.",
    "Drain or tube removal.",
    "Evaluation of surgical hernia."
  ],
  "Urology": [
    "Urinary incontinence evaluation or management.",
    "Evaluation of recurrent urinary tract infections.",
    "Evaluation of kidney stone, bladder stone, pain, or obstruction.",
    "Evaluation of prostate disorder, BPH, or prostate cancer concern.",
    "Evaluation of urinary retention, difficulty urinating, weak stream, or painful urination.",
    "Evaluation of hematuria or blood in urine.",
    "Catheter-related issue, long-term catheter need, or catheter complication.",
    "Follow-up after urologic surgery.",
    "Urologic surgical procedure follow-up.",
    "Cystoscopy evaluation or follow-up.",
    "Ureteral or urinary stent removal.",
    "Urologic biopsy follow-up or evaluation.",
    "Penile lesion evaluation.",
    "Urinary retention requiring specialist evaluation."
  ],
  "Vascular": [
    "Peripheral artery disease evaluation or management.",
    "Evaluation of venous insufficiency, varicose veins, leg swelling, or skin changes.",
    "Aneurysm monitoring or follow-up.",
    "Blood flow assessment for cold limb, discoloration, or non-healing wound.",
    "Post-vascular surgery or stent follow-up.",
    "DVT evaluation, screening, or follow-up.",
    "Vascular ulcer or wound care evaluation.",
    "Doppler ultrasound, angiography, or specialized vascular imaging.",
    "Angiography follow-up or evaluation.",
    "Angioplasty follow-up or evaluation."
  ],
  "Vascular Access": [
    "Dialysis access evaluation or management of AV fistula/graft.",
    "Central venous catheter placement or removal.",
    "Evaluation of vascular access infection, clotting, poor blood flow, or malfunction.",
    "Routine access monitoring for patency and function.",
    "Pre-surgical evaluation for new dialysis or infusion access.",
    "Interventional procedure such as angioplasty or thrombectomy for access function.",
    "Vascular access placement for chemotherapy, antibiotics, TPN, or long-term therapy.",
    "Follow-up after hospitalization or procedure involving vascular access."
  ],
  "Physiatry / Physical Medicine & Rehabilitation": [
    "Rehabilitation planning after illness, hospitalization, injury, or functional decline.",
    "Post-stroke recovery and mobility optimization.",
    "Chronic musculoskeletal or neuropathic pain management.",
    "Evaluation of mobility, gait, transfers, or assistive device needs.",
    "Evaluation of arthritis, muscle weakness, spasticity, or contractures.",
    "Spinal cord injury-related functional management.",
    "Functional decline assessment and ADL improvement planning.",
    "Coordination of PT, OT, and ST therapy services.",
    "Evaluation for new therapy equipment or assistive device."
  ],
  "Wound Care": [
    "Evaluation and treatment of chronic non-healing wound.",
    "Management of infected wound or suspected wound infection.",
    "Post-surgical wound follow-up.",
    "Debridement evaluation or need for advanced wound treatment.",
    "Specialized dressing recommendation or advanced dressing management.",
    "Negative pressure wound therapy evaluation or management.",
    "Evaluation of circulation issues affecting wound healing.",
    "Pain or symptom management related to wound care.",
    "Evaluation of worsening, enlarging, or deteriorating wound."
  ],
  "Neurosurgery": [
    "Evaluation of chronic back pain or neck pain requiring surgical review.",
    "Follow-up after brain or spine surgery.",
    "Evaluation of spinal stenosis, herniated disc, degenerative spine disease, or spinal disorder.",
    "Assessment of brain tumor or abnormal brain imaging.",
    "Hydrocephalus or shunt evaluation/management.",
    "Follow-up after traumatic brain injury or spine injury.",
    "Evaluation of severe neurologic symptoms such as headache, weakness, or loss of function.",
    "Review of MRI, CT scan, or imaging requiring neurosurgical interpretation.",
    "Evaluation of compression fracture requiring surgical review."
  ],
  "Rheumatology": [
    "Evaluation of persistent joint pain not improving with basic care.",
    "Evaluation of morning stiffness or limited mobility suspicious for inflammatory condition.",
    "Evaluation of joint swelling, inflammation, or suspected autoimmune arthritis.",
    "Evaluation of unexplained fatigue, rash, dry eyes, or systemic autoimmune symptoms.",
    "Evaluation of reduced range of motion due to stiffness, pain, or inflammation.",
    "Evaluation of abnormal autoimmune or inflammatory labs such as ANA, RF, ESR, or CRP.",
    "Follow-up for known autoimmune or rheumatologic disease.",
    "Osteoporosis or metabolic bone disease management.",
    "Evaluation of gout flare.",
    "Evaluation of polymyalgia rheumatica."
  ],
  "Outpatient Diagnostic Studies": [
    "MRI",
    "CT scan",
    "Bone density scan",
    "PET scan",
    "Sleep study",
    "Mammogram",
    "X-ray",
    "Ultrasound",
    "Stress test",
    "Biopsy",
    "Vascular Doppler study",
    "Modified barium swallow study / MBSS"
  ]
};
