export const MEDICAL_SPECIALTIES = [
  "Dental",
  "Cardiology",
  "Optometry",
  "Ophthalmology",
  "Audiology",
  "ENT",
  "Dermatology",
  "Endocrinology",
  "Gastroenterology / GI",
  "Hematology",
  "Oncology",
  "Infectious Disease",
  "Nephrology",
  "Neurology",
  "Neuropsychology",
  "Psychology",
  "OB/GYN",
  "Orthopedics",
  "Podiatry",
  "Pulmonology",
  "Surgery / General Surgery",
  "Urology",
  "Vascular",
  "Vascular Access",
  "Physiatry / Physical Medicine & Rehabilitation",
  "Wound Care",
  "Neurosurgery",
  "Rheumatology",
  "Outpatient Diagnostic Studies",
] as const;

export type MedicalSpecialty = (typeof MEDICAL_SPECIALTIES)[number];
